https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html

In [ ]:
# Import necessary libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix



In [ ]:
# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target




In [ ]:
# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)




In [ ]:
# Create an MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)



In [ ]:
# Train the classifier
mlp.fit(X_train, y_train)



MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

In [ ]:
# Make predictions
y_pred = mlp.predict(X_test)



In [ ]:
# Print the results
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [ ]:
# Predict a new unknown instance
new_instance = np.array([[5.1, 3.5, 1.4, 0.2]])  # Replace this with your new data instance

predicted_class = mlp.predict(new_instance)

# Print the predicted class
print(f"The predicted class for the new instance is: {iris.target_names[predicted_class][0]}")

The predicted class for the new instance is: setosa
